---
name: Build & Test
description: Build the final container image and run tests on it

inputs:
  registry:
    description: Target registry to push the final image.
    default: "localhost:5000"
  namespace:
    description: Namespace of the container image.
    default: ansible
  final_image:
    description: Name of the final image.
    default: community-ansible-devspaces-image
  publish:
    description: Publish the image to ghcr.io
    default: "false"

runs:
  using: composite
  steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Prepare
      shell: bash
      run: |
        platform=${{ matrix.platform }}
        echo "PLATFORM_PAIR=${platform//\//-}" >> $GITHUB_ENV

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        # network=host driver-opt needed to push to local registry
        driver-opts: network=host

    - name: Build devspaces image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: ${{ github.workspace }}/context
        provenance: false
        file: ${{ github.workspace }}/Containerfile
        load: true
        tags: |
          ${{ inputs.namespace }}/${{ inputs.final_image }}:test
        platforms: ${{ matrix.platform }}
        cache-from: type=gha,scope=build-${{ env.PLATFORM_PAIR }}
        cache-to: type=gha,scope=build-${{ env.PLATFORM_PAIR }}

    - name: Push the built image to ghcr.io
      id: push
      if: ${{ inputs.publish == 'true' }}
      shell: bash
      run: |
        docker tag ${{ inputs.namespace }}/${{ inputs.final_image }}:test ghcr.io/${{ inputs.namespace }}/${{ inputs.final_image }}:latest
        docker push ghcr.io/${{ inputs.namespace }}/${{ inputs.final_image }}:latest
    # this step is ONLY needed for maintainence of self hosted runners
    - name: Cleanup docker
      shell: bash
      if: always()
      run: |
        docker system prune -af --volumes
