---
name: ci

concurrency:
    group: ${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

on:
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    runs-on: devtools-multiarch-builder

    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the container image
        uses: ansible/community-ansible-devspaces-image/.github/actions/build-release@main
        with:
          publish: 'true'
